
Jupyter server is running on: c39-03
Job starts at: Tue Mar  6 15:06:43 EST 2018

Step 1 :

If you are working in NYU campus, please open an iTerm window, run command

ssh -L 9400:localhost:9400 vl1019@prince.hpc.nyu.edu

If you are working off campus, you should already have ssh tunneling setup through HPC bastion host,
that you can directly login to prince with command

ssh vl1019@prince

Please open an iTerm window, run command

ssh -L 9400:localhost:9400 vl1019@prince

Step 2:

Keep the iTerm windows in the previouse step open. Now open browser, find the line with

The Jupyter Notebook is running at:

the URL is something: http://localhost:/?token=XXXXXXXX

you should be able to connect to jupyter notebook running remotly on prince compute node with above url

[I 15:06:46.970 NotebookApp] Writing notebook server cookie secret to /state/partition1/job-4787896/jupyter/notebook_cookie_secret
[I 15:06:47.939 NotebookApp] Serving notebooks from local directory: /home/vl1019
[I 15:06:47.939 NotebookApp] 0 active kernels 
[I 15:06:47.939 NotebookApp] The Jupyter Notebook is running at: http://localhost:9400/?token=fe64048df0370af72c0b2515496f3796db7c879b1d550a8e
[I 15:06:47.939 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:06:47.939 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:9400/?token=fe64048df0370af72c0b2515496f3796db7c879b1d550a8e
[I 15:07:17.370 NotebookApp] 302 GET /?token=fe64048df0370af72c0b2515496f3796db7c879b1d550a8e (::1) 0.84ms
[W 15:11:02.530 NotebookApp] The signatures database cannot be opened; maybe it is corrupted or encrypted. You may need to rerun your notebooks to ensure that they are trusted to run Javascript. The old signatures database has been renamed to /home/vl1019/.local/share/jupyter/nbsignatures.db.bak and a new one has been created.
[W 15:11:02.551 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb is not trusted
[W 15:11:02.640 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 21.79ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb
[I 15:11:03.501 NotebookApp] Kernel started: c6681858-ab46-44e6-b066-3165b1e3c5d1
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T15.11.04.541775.sqlite and a new file created.
[I 15:14:02.932 NotebookApp] 302 GET /?token=fe64048df0370af72c0b2515496f3796db7c879b1d550a8e (::1) 0.33ms
[W 15:14:14.100 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb is not trusted
[W 15:14:14.115 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 2.03ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb
[W 15:14:47.618 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/21feb.ipynb is not trusted
[W 15:14:47.629 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.89ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:14:48.313 NotebookApp] Kernel started: e5e141bd-d4a7-4070-adcd-fd5094d1b8cd
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T15.14.49.192832.sqlite and a new file created.
[I 15:16:48.784 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[W 15:16:48.785 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:18:48.612 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[W 15:18:48.613 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:20:50.077 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[W 15:20:50.078 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:24:48.801 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[W 15:24:48.801 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:26:49.130 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[W 15:26:49.131 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:27:04.690 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[W 15:27:04.690 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:28:27.857 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:28:48.438 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:28:48.469 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:28:48.499 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:28:48.499 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "88895",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:28:48.499 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 510.58ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:28:49.111 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:28:49.115 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:28:49.115 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:28:49.116 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "88895",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:28:49.116 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 580.05ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:30:48.812 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:30:48.817 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:30:48.818 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:30:48.818 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "85171",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:30:48.818 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 403.05ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:32:48.830 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:32:48.835 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:32:48.836 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:32:48.836 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "89789",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:32:48.836 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 354.96ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:34:48.833 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:34:48.837 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:34:48.838 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:34:48.839 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "86279",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:34:48.839 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 436.85ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:35:26.495 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:35:26.499 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:35:26.500 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:35:26.500 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:35:26.500 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 403.96ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:35:30.844 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:35:30.848 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:35:30.849 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:35:30.849 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:35:30.849 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 417.86ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:35:31.289 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:35:31.292 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:35:31.293 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:35:31.293 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:35:31.293 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 401.39ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:35:31.753 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:35:31.757 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:35:31.757 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:35:31.758 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:35:31.758 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 429.73ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:35:32.283 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:35:32.286 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:35:32.287 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:35:32.287 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:35:32.287 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 527.00ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:35:32.556 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:35:32.560 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:35:32.560 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:35:32.561 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:35:32.561 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 279.56ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:35:36.606 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[E 15:35:36.610 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:35:36.610 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/21feb.ipynb disk I/O error
[E 15:35:36.611 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:35:36.611 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 458.36ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[W 15:35:47.443 NotebookApp] File already exists: BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb
[W 15:35:47.443 NotebookApp] 409 PATCH /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 1.63ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[W 15:35:49.785 NotebookApp] File already exists: BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb
[W 15:35:49.786 NotebookApp] 409 PATCH /api/contents/BirdVox-70k_icassp2018/spl2018/21feb.ipynb (::1) 1.68ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/21feb.ipynb
[I 15:36:01.102 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 15:36:01.107 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:36:01.108 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 15:36:01.108 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:36:01.108 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 429.29ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 15:36:01.526 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 15:36:01.531 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:36:01.531 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 15:36:01.531 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:36:01.531 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 400.53ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 15:36:02.027 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 15:36:02.030 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:36:02.031 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 15:36:02.031 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86304",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:36:02.031 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 498.51ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 15:36:49.220 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 15:36:49.224 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:36:49.225 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 15:36:49.225 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86513",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:36:49.225 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 717.13ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 15:38:51.180 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 15:38:51.184 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:38:51.185 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 15:38:51.185 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86513",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:38:51.185 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 456.16ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 15:40:54.091 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 15:40:54.096 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:40:54.097 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 15:40:54.097 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86513",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:40:54.097 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 2296.42ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 15:42:57.227 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 15:42:57.231 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 15:42:57.232 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 15:42:57.233 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86513",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 15:42:57.233 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 1957.53ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 15:45:33.089 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 17:40:13.754 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:40:13.775 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:40:13.776 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:40:13.777 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86513",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:40:13.777 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 423.85ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[W 17:40:17.311 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 2.24ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 17:40:27.376 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:40:27.380 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:40:27.380 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:40:27.381 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "86786",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:40:27.381 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 476.96ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 17:42:18.657 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:42:18.662 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:42:18.663 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:42:18.663 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "87748",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520367242|23:username-localhost-9400|44:MjJhYWQyZjlhYjIzNGY2ZWI4NDYwYWZjYjJjYTE2NjE=|ce7ad626b2f9d59d7244f8d8354cb64d174963498f265827c3c9aeed1a65f11a\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:42:18.663 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 652.49ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[W 17:43:20.723 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb is not trusted
[W 17:43:20.748 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 2.26ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb
[W 17:43:28.419 NotebookApp] Unreadable Notebook: /home/vl1019/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "c...',)
[W 17:43:28.420 NotebookApp] 400 GET /api/contents/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb?type=notebook&_=1520376208140 (::1) 67.63ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[W 17:43:28.423 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.45ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[W 17:43:34.309 NotebookApp] Unreadable Notebook: /home/vl1019/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "c...',)
[W 17:43:34.310 NotebookApp] 400 GET /api/contents/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb?type=notebook&_=1520376214123 (::1) 5.15ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[W 17:43:34.349 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.74ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[I 17:45:21.248 NotebookApp] 302 GET /?token=fe64048df0370af72c0b2515496f3796db7c879b1d550a8e (::1) 0.44ms
[W 17:47:03.385 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb is not trusted
[W 17:47:03.419 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 2.12ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb
[W 17:47:22.795 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.73ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[W 17:47:26.119 NotebookApp] Unreadable Notebook: /home/vl1019/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "c...',)
[W 17:47:26.119 NotebookApp] 400 GET /api/contents/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb?type=notebook&_=1520376445982 (::1) 5.15ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[W 17:47:26.134 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.76ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[I 17:49:23.743 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:49:23.748 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:49:23.748 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:49:23.749 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "63120",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:49:23.749 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 294.94ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 17:51:23.945 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:51:23.949 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:51:23.950 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:51:23.950 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "96025",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:51:23.950 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 463.28ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 17:52:45.310 NotebookApp] Kernel restarted: e5e141bd-d4a7-4070-adcd-fd5094d1b8cd
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T17.52.46.192135.sqlite and a new file created.
[I 17:53:24.926 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:53:24.931 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:53:24.932 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:53:24.932 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "88906",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:53:24.932 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 425.64ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 17:55:24.922 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:55:24.926 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:55:24.927 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:55:24.928 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "88863",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:55:24.928 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 429.93ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 17:57:24.939 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:57:24.944 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:57:24.945 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:57:24.945 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "89972",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:57:24.945 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 453.29ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 17:59:24.958 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 17:59:24.962 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 17:59:24.962 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 17:59:24.963 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "96865",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 17:59:24.963 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 456.36ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:01:25.049 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:01:25.053 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:01:25.054 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:01:25.055 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "96237",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:01:25.055 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 462.59ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:03:26.862 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:03:26.866 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:03:26.867 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:03:26.868 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "95983",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:03:26.868 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 2105.78ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:04:33.618 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:04:33.622 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:04:33.623 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:04:33.624 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "96154",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:04:33.624 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 881.33ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:05:27.052 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:05:27.057 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:05:27.057 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:05:27.058 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94652",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:05:27.058 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 792.91ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:07:25.056 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:07:25.060 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:07:25.061 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:07:25.062 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94858",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:07:25.062 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 447.41ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[W 18:09:17.517 NotebookApp] Notebook BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb is not trusted
[W 18:09:17.547 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.79ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb
[I 18:09:19.030 NotebookApp] Kernel started: 61dfd293-f92b-4474-8335-ab8a0a9086f0
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T18.09.19.918275.sqlite and a new file created.
[I 18:09:25.062 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:09:25.067 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:09:25.067 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:09:25.068 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94858",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:09:25.068 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 442.50ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:11:28.142 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:11:28.148 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:11:28.149 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:11:28.150 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94858",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:11:28.150 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 2050.55ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:13:30.525 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:13:30.530 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:13:30.531 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:13:30.531 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94858",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:13:30.531 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 456.65ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:15:30.471 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:15:30.476 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:15:30.477 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:15:30.477 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "85025",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:15:30.477 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 431.79ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:17:30.531 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:17:30.539 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:17:30.540 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:17:30.541 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94483",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:17:30.541 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 454.03ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:19:30.511 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:19:30.516 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:19:30.516 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:19:30.517 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "95206",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:19:30.517 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 459.64ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:21:30.550 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:21:30.554 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:21:30.555 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:21:30.556 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "95282",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:21:30.556 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 484.64ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:23:30.376 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:23:30.381 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:23:30.381 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:23:30.382 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "66104",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:23:30.382 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 303.73ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:25:30.514 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:25:30.519 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:25:30.520 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:25:30.520 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "97490",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:25:30.520 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 453.30ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:27:30.534 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:27:30.539 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:27:30.540 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:27:30.540 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "97580",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:27:30.540 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 460.44ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:29:30.529 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:29:30.533 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:29:30.534 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:29:30.535 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "95636",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:29:30.535 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 450.43ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:31:30.530 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:31:30.534 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:31:30.535 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:31:30.536 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94386",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:31:30.536 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 454.21ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:33:30.530 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:33:30.535 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:33:30.536 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:33:30.536 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "95279",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:33:30.536 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 446.40ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:35:31.684 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:35:31.689 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:35:31.690 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:35:31.691 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94392",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:35:31.691 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 462.72ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:37:30.586 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:37:30.591 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:37:30.592 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:37:30.592 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94574",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:37:30.592 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 489.85ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:39:30.547 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:39:30.552 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:39:30.554 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:39:30.554 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94782",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:39:30.554 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 452.55ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:41:30.588 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:41:30.593 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:41:30.594 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:41:30.594 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94724",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:41:30.594 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 452.05ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:43:36.420 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:43:36.425 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:43:36.426 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:43:36.427 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94713",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:43:36.427 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 5163.28ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:45:30.619 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[W 18:46:01.220 NotebookApp] Notebook BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb is not trusted
[W 18:46:01.250 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.89ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb
[I 18:47:30.587 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:47:30.602 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:47:30.603 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:47:30.603 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94778",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:47:30.603 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 453.07ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:49:30.594 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:49:30.606 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:49:30.607 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:49:30.608 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94888",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:49:30.608 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 326.51ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:51:30.568 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:51:30.572 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:51:30.574 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:51:30.574 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "93409",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:51:30.574 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 431.97ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:53:33.064 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:53:33.074 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:53:33.075 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:53:33.076 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92843",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:53:33.076 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 2180.64ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:55:30.343 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:55:30.347 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:55:30.348 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:55:30.349 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "43503",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:55:30.349 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 207.19ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:57:30.622 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:57:30.627 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:57:30.628 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:57:30.629 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92585",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:57:30.629 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 468.26ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 18:59:30.617 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 18:59:30.622 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 18:59:30.623 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 18:59:30.623 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92589",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 18:59:30.623 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 466.18ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 19:01:30.598 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 19:01:30.607 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:01:30.608 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 19:01:30.609 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92589",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:01:30.609 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 438.59ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 19:03:30.598 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 19:03:30.603 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:03:30.604 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 19:03:30.605 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92589",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:03:30.605 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 434.80ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 19:05:30.639 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 19:05:30.672 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:05:30.673 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 19:05:30.674 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92589",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:05:30.674 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 501.38ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 19:07:30.606 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 19:07:30.636 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:07:30.637 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 19:07:30.637 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92589",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:07:30.637 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 470.28ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 19:09:33.732 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 19:09:33.744 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:09:33.745 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 19:09:33.746 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92589",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:09:33.746 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 448.03ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 19:11:34.196 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 19:11:34.217 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:11:34.218 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 19:11:34.219 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "92589",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:11:34.219 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 480.25ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[W 19:13:47.703 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/pcen_snr.ipynb is not trusted
[W 19:13:47.720 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.98ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/pcen_snr.ipynb
[I 19:13:48.014 NotebookApp] Kernel started: 297c9725-ad90-493b-a04c-4fb34c7d4763
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T19.13.48.901337.sqlite and a new file created.
[W 19:14:23.557 NotebookApp] Unreadable Notebook: /home/vl1019/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "c...',)
[W 19:14:23.558 NotebookApp] 400 GET /api/contents/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb?type=notebook&_=1520381663397 (::1) 4.90ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[W 19:14:23.577 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.70ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[W 19:18:12.394 NotebookApp] Unreadable Notebook: /home/vl1019/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "c...',)
[W 19:18:12.394 NotebookApp] 400 GET /api/contents/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb?type=notebook&_=1520381891191 (::1) 5.15ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[W 19:18:12.920 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 2.19ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_recall-time.ipynb
[I 19:18:19.041 NotebookApp] Creating new notebook in /BirdVox-70k_icassp2018/spl2018
[E 19:18:19.045 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/Untitled.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:18:19.045 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/Untitled.ipynb disk I/O error
[E 19:18:19.046 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/tree/BirdVox-70k_icassp2018/spl2018",
      "Content-Length": "19",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:18:19.046 NotebookApp] 500 POST /api/contents/BirdVox-70k_icassp2018/spl2018 (::1) 5.28ms referer=http://localhost:9400/tree/BirdVox-70k_icassp2018/spl2018
[I 19:18:27.532 NotebookApp] Creating new notebook in /BirdVox-70k_icassp2018/spl2018
[E 19:18:27.535 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/Untitled.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:18:27.536 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/Untitled.ipynb disk I/O error
[E 19:18:27.536 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/tree/BirdVox-70k_icassp2018/spl2018",
      "Content-Length": "19",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:18:27.536 NotebookApp] 500 POST /api/contents/BirdVox-70k_icassp2018/spl2018 (::1) 5.13ms referer=http://localhost:9400/tree/BirdVox-70k_icassp2018/spl2018
[I 19:18:42.604 NotebookApp] Creating new notebook in /BirdVox-70k_icassp2018/icassp2018
[E 19:18:42.628 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/icassp2018/Untitled.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:18:42.629 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/icassp2018/Untitled.ipynb disk I/O error
[E 19:18:42.629 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb",
      "Content-Length": "19",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520376321|23:username-localhost-9400|44:NTZjZjUxNDE2YjEzNGZlZTkxMDc2ZjNkYWIxZTI4YjI=|540db7fb9df4da92dff245949a2232b28e27cf28c8d4e2a85bb67b6956e7316f\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:18:42.629 NotebookApp] 500 POST /api/contents/BirdVox-70k_icassp2018/icassp2018 (::1) 25.98ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb
[I 19:29:51.934 NotebookApp] 302 GET /?token=fe64048df0370af72c0b2515496f3796db7c879b1d550a8e (::1) 0.35ms
[W 19:31:15.840 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb is not trusted
[W 19:31:15.860 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.88ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 19:31:16.749 NotebookApp] Kernel started: bd75aae0-4a50-47ea-ac4e-802b60b22f14
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T19.31.17.622213.sqlite and a new file created.
[I 19:31:34.307 NotebookApp] Kernel restarted: bd75aae0-4a50-47ea-ac4e-802b60b22f14
[W 19:31:34.311 NotebookApp] zmq message arrived on closed channel
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T19.31.35.132783.sqlite and a new file created.
[I 19:33:17.689 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:33:17.690 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 19:35:17.689 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:35:17.690 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 19:37:17.657 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:37:17.658 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 19:39:17.659 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:39:17.660 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:46:20.040 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb is not trusted
[W 19:46:20.052 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 2.03ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb
[W 19:46:47.621 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.64ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[I 19:47:17.923 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:47:17.924 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:47:46.188 NotebookApp] Notebook BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb is not trusted
[W 19:47:46.232 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 2.34ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/fig_precision-recall.ipynb
[I 19:48:01.296 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[E 19:48:01.301 NotebookApp] Error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
    Traceback (most recent call last):
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 447, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/home/vl1019/miniconda3/lib/python3.6/site-packages/nbformat/sign.py", line 220, in store_signature
        n, = self.db.execute("SELECT Count(*) FROM nbsignatures").fetchone()
    sqlite3.OperationalError: disk I/O error
[W 19:48:01.301 NotebookApp] Unexpected error while saving file: BirdVox-70k_icassp2018/spl2018/6-mars.ipynb disk I/O error
[E 19:48:01.302 NotebookApp] {
      "Host": "localhost:9400",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:9400",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",
      "Referer": "http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb",
      "Content-Length": "94430",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-9400=\"2|1:0|10:1520382591|23:username-localhost-9400|44:YTM4ZGI3NzRhMjRlNDI0MmJjOThkNWI0NTc2NTI0NTA=|a7ef98835032b9967587068f7899b83b2f9de780342ca8fd6de73f642fa78a0b\"; username-localhost-8888=\"2|1:0|10:1520367103|23:username-localhost-8888|44:OGZlMjRiMmExZjMxNDg2Yzk5YzczMmQzNTJiOWQzMWQ=|a50594862452ca6891d778ffa2f1636b87f0ce14254ba31c2b003a0bbc18f8c4\"; username-localhost-6918=\"2|1:0|10:1520220349|23:username-localhost-6918|44:NjY2NjEzNzcyMTJhNGNmM2E4NDI2ZmIzZmEwMzkzMmE=|3da88256b7036ac0703277fe9c126d7f7da8eacf47e1f31ec6d51357a30cbb89\"; _xsrf=2|53c77471|7a5ab5bd8ff2ea36ecb9d34be00b4789|1520208114"
    }
[E 19:48:01.302 NotebookApp] 500 PUT /api/contents/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb (::1) 459.67ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/spl2018/6-mars.ipynb
[W 19:48:33.908 NotebookApp] Notebook BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb is not trusted
[W 19:48:33.949 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.85ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb
[W 19:48:45.901 NotebookApp] Notebook BirdVox-70k_icassp2018/icassp2018/fig_recall-frequency.ipynb is not trusted
[W 19:48:45.921 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.70ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/icassp2018/fig_recall-frequency.ipynb
[I 19:48:46.256 NotebookApp] Kernel started: 835dce17-e73e-40b1-bd58-c37853f47a03
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T19.48.47.135429.sqlite and a new file created.
[W 19:49:00.773 NotebookApp] Notebook BirdVox-70k_icassp2018/icassp2018/fig_binary-classification.ipynb is not trusted
[W 19:49:00.784 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.87ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/icassp2018/fig_binary-classification.ipynb
[I 19:49:01.167 NotebookApp] Kernel started: 53ec7feb-741b-4f44-a011-f62c9756591d
[IPKernelApp] ERROR | Failed to open SQLite history /home/vl1019/.ipython/profile_default/history.sqlite (disk I/O error).
[IPKernelApp] ERROR | History file was moved to /home/vl1019/.ipython/profile_default/history-corrupt-2018-03-06T19.49.01.989235.sqlite and a new file created.
[W 19:49:12.609 NotebookApp] Notebook BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb is not trusted
[W 19:49:12.639 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180306150646 (::1) 1.65ms referer=http://localhost:9400/notebooks/BirdVox-70k_icassp2018/icassp2018/fig_precision-recall.ipynb
[I 19:51:17.887 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:51:17.888 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 19:53:20.448 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:53:20.449 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 19:55:19.292 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:55:19.293 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 19:59:17.913 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 19:59:17.914 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 20:01:17.973 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 20:01:17.974 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[I 20:03:17.978 NotebookApp] Saving file at /BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 20:03:17.979 NotebookApp] Saving untrusted notebook BirdVox-70k_icassp2018/spl2018/fig_binary-classification.ipynb
[W 20:17:05.256 NotebookApp] WebSocket ping timeout after 119879 ms.
[W 20:17:14.248 NotebookApp] WebSocket ping timeout after 119954 ms.
[W 20:17:17.058 NotebookApp] WebSocket ping timeout after 119977 ms.
slurmstepd: error: *** JOB 4787896 ON c39-03 CANCELLED AT 2018-03-06T23:59:26 ***
